### ISSUE TITLE
3 permission limit?

### ISSUE THREAD

**Issue by rlaferla** [nickoneill/PermissionScope#116] opened 2015-11-03 05:00 UTC
So if your app needs more than three permissions, PermissionScope doesn't work?  I need four and possibly more.

```
assertion failed: Ask for three or fewer permissions at a time
```

**Comment by nickoneill** [comment] 2015-11-03 15:49
You should still be asking for permissions contextually, as the app needs to access various components, rather than all the permissions upfront. The design supports this hypothesis by limiting the number of permissions you can request at one time to 3.

You can (and should) create a different instance of permissionscope when you're asking for different permissions and present those. To support this workflow, we support showing the status of already asked for permissions as "disabled," "denied" or "accepted."

**Comment by rlaferla** [comment] 2015-11-03 16:04
I create one PermissionScope instance in the app delegate that is shared by the rest of the app.  During creation, permissions are added and it's at that time when the assert kicks in.

**Comment by rlaferla** [comment] 2015-11-03 16:09
I like configuring the permissions once and calling up the dialog.  Perhaps, I can take a slightly different approach and create instances of each Permission in the app delegate and then add them to scope instances.  

I think there may be a design improvement here. How about if PermissionScope had a dictionary of permissions and you could toggle which ones are displayed?  The key for the dictionary being "contacts", "location", etc...

**Comment by bre7** [comment] 2015-11-03 16:12
> I think there may be a design improvement here. How about if PermissionScope had a dictionary of permissions and you could toggle which ones are displayed?  The key for the dictionary being "contacts", "location", etc...

The problem is that some status methods require arguments

**Comment by rlaferla** [comment] 2015-11-03 16:14
Please elaborate.

**Comment by nickoneill** [comment] 2015-11-03 16:18
> I think there may be a design improvement here. How about if PermissionScope had a dictionary of permissions and you could toggle which ones are displayed? The key for the dictionary being "contacts", "location", etc...

I don't see the benefit of switching to this model when you can achieve the same thing with our current model by adding multiple instances of permissionscope to any view controllers you need them in. In general, relying on state management in a singleton like the app delegate is frowned upon.

**Comment by rlaferla** [comment] 2015-11-03 16:23
Also, I think "message" should be an attribute of "Permission" rather than an additional argument when you add it to the scope.    In fact, the scope could be a dictionary and you could configure the message for each type ("contacts", "location", etc...) and whether or not it was enabled.  However, I need to better understand what other required arguments there are.

**Comment by rlaferla** [comment] 2015-11-03 16:26
For one, localization and message consistency.  It is beneficial to configure the messages in one place (perhaps with some flexibility of having alternate messages - but that's an exception case).  Another is memory usage.

**Comment by bre7** [comment] 2015-11-03 16:29
The _message_ is related to the UI, I don't think it's right to send/store it when creating the Permission itself since it won't be used.

> However, I need to better understand what other required arguments there are. 

Notifications and Health (removed for the time being) for instance.

**Comment by bre7** [comment] 2016-10-11 23:16
Closing for the time being.

**Closed as completed by bre7** 2016-10-11 23:16 UTC
Labels: question
